// Generated by `pnpm data:update-db` from `data/hotend data.csv`. Do not edit by hand.

import type { HotendDefinition } from '@/lib/hotend';
import type { Celsius, Dollars, Millimeter } from '@/lib/units';

export const HOTEND_DB: HotendDefinition[] = [
	{
		id: 'A3DP|HE20',
		manufacturer: 'A3DP',
		name: 'HE20',
		ecosystem: 'Takoto',
		mountingPattern: 'A3DP',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 26 as Millimeter,
		price: 160 as Dollars
	},
	{
		id: 'A3DP|HE50',
		manufacturer: 'A3DP',
		name: 'HE50',
		ecosystem: 'Takoto',
		mountingPattern: 'A3DP',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 53 as Millimeter,
		price: 210 as Dollars
	},
	{
		id: 'Bambulab|X1C OEM hotend',
		manufacturer: 'Bambulab',
		name: 'X1C OEM hotend',
		ecosystem: 'X1C',
		mountingPattern: 'X1C',
		nozzle: 'TZ',
		mzeCompatible: false,
		hfNozzleCompatible: false,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 24.2 as Millimeter,
		price: 20 as Dollars
	},
	{
		id: 'Bondtech|INDX',
		manufacturer: 'Bondtech',
		name: 'INDX',
		ecosystem: 'INDX',
		mountingPattern: 'INDX',
		nozzle: 'Proprietary',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'St', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 28 as Millimeter,
		price: 45 as Dollars
	},
	{
		id: 'Brumpo Tungus|brumpo hotend',
		manufacturer: 'Brumpo Tungus',
		name: 'brumpo hotend',
		ecosystem: null,
		mountingPattern: null,
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 74.5 as Millimeter,
		price: null
	},
	{
		id: 'Brumpo Tungus|Brumpo WC hotend',
		manufacturer: 'Brumpo Tungus',
		name: 'Brumpo WC hotend',
		ecosystem: null,
		mountingPattern: null,
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 50 as Millimeter,
		price: null
	},
	{
		id: 'E3D|Revo',
		manufacturer: 'E3D',
		name: 'Revo',
		ecosystem: 'Revo',
		mountingPattern: 'Revo',
		nozzle: 'Revo',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Br', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 19.6 as Millimeter,
		price: 95 as Dollars
	},
	{
		id: 'E3D|supervolcano',
		manufacturer: 'E3D',
		name: 'supervolcano',
		ecosystem: 'V6',
		mountingPattern: 'Groove',
		nozzle: 'V6 Supervolcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius },
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 57.5 as Millimeter,
		price: 30 as Dollars
	},
	{
		id: 'E3D|v6',
		manufacturer: 'E3D',
		name: 'v6',
		ecosystem: 'V6',
		mountingPattern: 'Groove',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius },
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 17.5 as Millimeter,
		price: 8 as Dollars
	},
	{
		id: 'E3D|v6 volcano',
		manufacturer: 'E3D',
		name: 'v6 volcano',
		ecosystem: 'V6',
		mountingPattern: 'Groove',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius },
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 26 as Millimeter,
		price: 12 as Dollars
	},
	{
		id: 'Elegoo|Centauri Carbon',
		manufacturer: 'Elegoo',
		name: 'Centauri Carbon',
		ecosystem: 'CC',
		mountingPattern: 'CC',
		nozzle: 'Proprietary',
		mzeCompatible: false,
		hfNozzleCompatible: false,
		blockOptions: [
			{ material: 'Br', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 35.5 as Millimeter,
		price: 9 as Dollars
	},
	{
		id: 'Generic|TZ HF (MZE+V6)',
		manufacturer: 'Generic',
		name: 'TZ HF (MZE+V6)',
		ecosystem: 'X1C',
		mountingPattern: 'X1C',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 34.5 as Millimeter,
		price: 22 as Dollars
	},
	{
		id: 'Generic|TZ hotends',
		manufacturer: 'Generic',
		name: 'TZ hotends',
		ecosystem: 'X1C',
		mountingPattern: 'X1C',
		nozzle: 'TZ',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 24.2 as Millimeter,
		price: 12 as Dollars
	},
	{
		id: 'Generic|TZ2.0-V6',
		manufacturer: 'Generic',
		name: 'TZ2.0-V6',
		ecosystem: 'Generic',
		mountingPattern: 'Dragon',
		nozzle: 'TZ',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 25.35 as Millimeter,
		price: 12 as Dollars
	},
	{
		id: 'Generic|TZ2.0-V6 HF (MZE+V6)',
		manufacturer: 'Generic',
		name: 'TZ2.0-V6 HF (MZE+V6)',
		ecosystem: 'Generic',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 35.65 as Millimeter,
		price: 22 as Dollars
	},
	{
		id: 'Lukes Lab|chube air',
		manufacturer: 'Lukes Lab',
		name: 'chube air',
		ecosystem: 'Chube',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 46 as Millimeter,
		price: 260 as Dollars
	},
	{
		id: 'Lukes Lab|chube compact',
		manufacturer: 'Lukes Lab',
		name: 'chube compact',
		ecosystem: 'Chube',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 38.5 as Millimeter,
		price: 165 as Dollars
	},
	{
		id: 'Lukes Lab|chube conduction',
		manufacturer: 'Lukes Lab',
		name: 'chube conduction',
		ecosystem: 'Chube',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 56 as Millimeter,
		price: 320 as Dollars
	},
	{
		id: 'Lukes Lab|Pika',
		manufacturer: 'Lukes Lab',
		name: 'Pika',
		ecosystem: 'X1C',
		mountingPattern: 'X1C',
		nozzle: 'Fin',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 33 as Millimeter,
		price: 125 as Dollars
	},
	{
		id: 'Mellow|goliath',
		manufacturer: 'Mellow',
		name: 'goliath',
		ecosystem: 'Vzbot',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 51.15 as Millimeter,
		price: 120 as Dollars
	},
	{
		id: 'Mellow|NF Crazy',
		manufacturer: 'Mellow',
		name: 'NF Crazy',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 18.5 as Millimeter,
		price: 41 as Dollars
	},
	{
		id: 'Mellow|NF Crazy HF',
		manufacturer: 'Mellow',
		name: 'NF Crazy HF',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 25 as Millimeter,
		price: 44 as Dollars
	},
	{
		id: 'Mellow|NF Crazy HF Volcano',
		manufacturer: 'Mellow',
		name: 'NF Crazy HF Volcano',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 34.5 as Millimeter,
		price: 50 as Dollars
	},
	{
		id: 'Mellow|NF Crazy Volcano',
		manufacturer: 'Mellow',
		name: 'NF Crazy Volcano',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 28 as Millimeter,
		price: 48 as Dollars
	},
	{
		id: 'Metaform|Pico hotend',
		manufacturer: 'Metaform',
		name: 'Pico hotend',
		ecosystem: 'V6',
		mountingPattern: 'Groove',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius },
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 20.55 as Millimeter,
		price: 100 as Dollars
	},
	{
		id: 'Microswiss|Flowtech',
		manufacturer: 'Microswiss',
		name: 'Flowtech',
		ecosystem: 'Various',
		mountingPattern: 'Various',
		nozzle: 'Proprietary',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 28.6 as Millimeter,
		price: 80 as Dollars
	},
	{
		id: 'Peopoly|Lancer long',
		manufacturer: 'Peopoly',
		name: 'Lancer long',
		ecosystem: 'Lancer',
		mountingPattern: 'Lancer',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 45 as Millimeter,
		price: 37.5 as Dollars
	},
	{
		id: 'Peopoly|Lancer short',
		manufacturer: 'Peopoly',
		name: 'Lancer short',
		ecosystem: 'Lancer',
		mountingPattern: 'Lancer',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 28 as Millimeter,
		price: 22.5 as Dollars
	},
	{
		id: 'Peopoly|Lancer standard',
		manufacturer: 'Peopoly',
		name: 'Lancer standard',
		ecosystem: 'Lancer',
		mountingPattern: 'Lancer',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 36.5 as Millimeter,
		price: 30 as Dollars
	},
	{
		id: 'Phaetus|dragon',
		manufacturer: 'Phaetus',
		name: 'dragon',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 26 as Millimeter,
		price: 55 as Dollars
	},
	{
		id: 'Phaetus|dragon HF',
		manufacturer: 'Phaetus',
		name: 'dragon HF',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 33.5 as Millimeter,
		price: 60 as Dollars
	},
	{
		id: 'Phaetus|dragon volcano',
		manufacturer: 'Phaetus',
		name: 'dragon volcano',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 34.5 as Millimeter,
		price: 65 as Dollars
	},
	{
		id: 'Phaetus|dragon volcano UHF',
		manufacturer: 'Phaetus',
		name: 'dragon volcano UHF',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 35.5 as Millimeter,
		price: 70 as Dollars
	},
	{
		id: 'Phaetus|dragon volcano UUHF',
		manufacturer: 'Phaetus',
		name: 'dragon volcano UUHF',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 43 as Millimeter,
		price: 75 as Dollars
	},
	{
		id: 'Phaetus|Rapido UHF',
		manufacturer: 'Phaetus',
		name: 'Rapido UHF',
		ecosystem: 'Rapido',
		mountingPattern: 'Dragon',
		nozzle: 'V6 Volcano',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 34 as Millimeter,
		price: 90 as Dollars
	},
	{
		id: 'Slice Engineering|mosquito',
		manufacturer: 'Slice Engineering',
		name: 'mosquito',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 18.5 as Millimeter,
		price: 150 as Dollars
	},
	{
		id: 'Slice Engineering|mosquito magnum',
		manufacturer: 'Slice Engineering',
		name: 'mosquito magnum',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 25 as Millimeter,
		price: 175 as Dollars
	},
	{
		id: 'Slice Engineering|mosquito magnum+',
		manufacturer: 'Slice Engineering',
		name: 'mosquito magnum+',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 38.7 as Millimeter,
		price: 369 as Dollars
	},
	{
		id: 'Slice Engineering|mosquito magnum+ HF',
		manufacturer: 'Slice Engineering',
		name: 'mosquito magnum+ HF',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 45.2 as Millimeter,
		price: 423 as Dollars
	},
	{
		id: 'Slice Engineering|mosquito prime',
		manufacturer: 'Slice Engineering',
		name: 'mosquito prime',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 66.7 as Millimeter,
		price: 1577 as Dollars
	},
	{
		id: 'Trianglelab|CHC XP1',
		manufacturer: 'Trianglelab',
		name: 'CHC XP1',
		ecosystem: 'X1C',
		mountingPattern: 'X1C',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 35 as Millimeter,
		price: 44 as Dollars
	},
	{
		id: 'Trianglelab|dragon ace',
		manufacturer: 'Trianglelab',
		name: 'dragon ace',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 36.2 as Millimeter,
		price: 80 as Dollars
	},
	{
		id: 'Trianglelab|dragon ace volcano',
		manufacturer: 'Trianglelab',
		name: 'dragon ace volcano',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 44.7 as Millimeter,
		price: 85 as Dollars
	},
	{
		id: 'Unknown|Lattice hotend',
		manufacturer: 'Unknown',
		name: 'Lattice hotend',
		ecosystem: null,
		mountingPattern: null,
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 57.9 as Millimeter,
		price: null
	},
	{
		id: 'Unknown|MK8',
		manufacturer: 'Unknown',
		name: 'MK8',
		ecosystem: 'MK8',
		mountingPattern: 'MK8',
		nozzle: 'MK8',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 500 as Celsius },
			{ material: 'Cu', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 18.8 as Millimeter,
		price: 8 as Dollars
	},
	{
		id: 'Unknown|Tricorn',
		manufacturer: 'Unknown',
		name: 'Tricorn',
		ecosystem: null,
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 53 as Millimeter,
		price: 200 as Dollars
	},
	{
		id: 'Unknown|V9',
		manufacturer: 'Unknown',
		name: 'V9',
		ecosystem: null,
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 39.5 as Millimeter,
		price: 220 as Dollars
	}
];
