// Generated by `pnpm data:update-db` from `data/hotend data.csv`. Do not edit by hand.

import type { HotendDefinition } from '@/lib/hotend';
import type { Celsius, Dollars, Millimeter } from '@/lib/units';

export const HOTEND_DB: HotendDefinition[] = [
	{
		id: 'A3DP|HE20',
		manufacturer: 'A3DP',
		name: 'HE20',
		ecosystem: 'Takoto',
		mountingPattern: 'A3DP',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 26 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 160 as Dollars
	},
	{
		id: 'A3DP|HE50',
		manufacturer: 'A3DP',
		name: 'HE50',
		ecosystem: 'Takoto',
		mountingPattern: 'A3DP',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 53 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 210 as Dollars
	},
	{
		id: 'Bambulab|A1 Hotend',
		manufacturer: 'Bambulab',
		name: 'A1 Hotend',
		ecosystem: 'A1',
		mountingPattern: 'A1',
		nozzle: 'Integrated',
		mzeCompatible: false,
		hfNozzleCompatible: false,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 27.2 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 10 as Dollars
	},
	{
		id: 'Bambulab|H2 Hotend',
		manufacturer: 'Bambulab',
		name: 'H2 Hotend',
		ecosystem: 'H2',
		mountingPattern: 'H2',
		nozzle: 'Integrated',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 33 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 18 as Dollars
	},
	{
		id: 'Bambulab|X1C OEM Hotend',
		manufacturer: 'Bambulab',
		name: 'X1C OEM Hotend',
		ecosystem: 'X1C',
		mountingPattern: 'X1C',
		nozzle: 'Integrated',
		mzeCompatible: false,
		hfNozzleCompatible: false,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 24.2 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 20 as Dollars
	},
	{
		id: 'Bondtech|INDX',
		manufacturer: 'Bondtech',
		name: 'INDX',
		ecosystem: 'INDX',
		mountingPattern: 'INDX',
		nozzle: 'Integrated',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'St', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 28 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 45 as Dollars
	},
	{
		id: 'Brumpo Tungus|Brumpo Hotend',
		manufacturer: 'Brumpo Tungus',
		name: 'Brumpo Hotend',
		ecosystem: null,
		mountingPattern: null,
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 74.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: null
	},
	{
		id: 'Brumpo Tungus|Brumpo WC Hotend',
		manufacturer: 'Brumpo Tungus',
		name: 'Brumpo WC Hotend',
		ecosystem: null,
		mountingPattern: null,
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 50 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: null
	},
	{
		id: 'Causality Manufacturing|Vesivius',
		manufacturer: 'Causality Manufacturing',
		name: 'Vesivius',
		ecosystem: null,
		mountingPattern: null,
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'St', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 92 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: null
	},
	{
		id: 'Dyze|Typhoon',
		manufacturer: 'Dyze',
		name: 'Typhoon',
		ecosystem: null,
		mountingPattern: 'Dyze',
		nozzle: 'Proprietary',
		mzeCompatible: false,
		hfNozzleCompatible: false,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 114 as Millimeter,
		filamentDiameter: 2.85 as Millimeter,
		price: 2700 as Dollars
	},
	{
		id: 'E3D|Revo',
		manufacturer: 'E3D',
		name: 'Revo',
		ecosystem: 'Revo',
		mountingPattern: 'Revo',
		nozzle: 'Revo',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'Br', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 19.6 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 95 as Dollars
	},
	{
		id: 'E3D|Supervolcano',
		manufacturer: 'E3D',
		name: 'Supervolcano',
		ecosystem: 'V6',
		mountingPattern: 'Groove',
		nozzle: 'V6 Supervolcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius },
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 57.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 30 as Dollars
	},
	{
		id: 'E3D|V6',
		manufacturer: 'E3D',
		name: 'V6',
		ecosystem: 'V6',
		mountingPattern: 'Groove',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius },
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 17.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 8 as Dollars
	},
	{
		id: 'E3D|V6 Volcano',
		manufacturer: 'E3D',
		name: 'V6 Volcano',
		ecosystem: 'V6',
		mountingPattern: 'Groove',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius },
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 26 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 12 as Dollars
	},
	{
		id: 'Elegoo|Centauri Carbon',
		manufacturer: 'Elegoo',
		name: 'Centauri Carbon',
		ecosystem: 'CC',
		mountingPattern: 'CC',
		nozzle: 'Proprietary',
		mzeCompatible: false,
		hfNozzleCompatible: false,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'Br', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 35.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 9 as Dollars
	},
	{
		id: 'Generic|TZ HF (MZE+V6)',
		manufacturer: 'Generic',
		name: 'TZ HF (MZE+V6)',
		ecosystem: 'X1C',
		mountingPattern: 'X1C',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 34.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 22 as Dollars
	},
	{
		id: 'Generic|TZ Hotends',
		manufacturer: 'Generic',
		name: 'TZ Hotends',
		ecosystem: 'X1C',
		mountingPattern: 'X1C',
		nozzle: 'TZ',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 24.2 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 12 as Dollars
	},
	{
		id: 'Generic|TZ2.0-V6',
		manufacturer: 'Generic',
		name: 'TZ2.0-V6',
		ecosystem: 'Generic',
		mountingPattern: 'Dragon',
		nozzle: 'TZ',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 25.35 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 12 as Dollars
	},
	{
		id: 'Generic|TZ2.0-V6 HF (MZE+V6)',
		manufacturer: 'Generic',
		name: 'TZ2.0-V6 HF (MZE+V6)',
		ecosystem: 'Generic',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 35.65 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 22 as Dollars
	},
	{
		id: 'Lukes Lab|Chube Air',
		manufacturer: 'Lukes Lab',
		name: 'Chube Air',
		ecosystem: 'Chube',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 46 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 260 as Dollars
	},
	{
		id: 'Lukes Lab|Chube Compact',
		manufacturer: 'Lukes Lab',
		name: 'Chube Compact',
		ecosystem: 'Chube',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 38.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 165 as Dollars
	},
	{
		id: 'Lukes Lab|Chube Conduction',
		manufacturer: 'Lukes Lab',
		name: 'Chube Conduction',
		ecosystem: 'Chube',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 56 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 320 as Dollars
	},
	{
		id: 'Lukes Lab|Pika',
		manufacturer: 'Lukes Lab',
		name: 'Pika',
		ecosystem: 'X1C',
		mountingPattern: 'X1C',
		nozzle: 'Fin',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 33 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 125 as Dollars
	},
	{
		id: 'Mellow|Goliath',
		manufacturer: 'Mellow',
		name: 'Goliath',
		ecosystem: 'Vzbot',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 51.15 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 120 as Dollars
	},
	{
		id: 'Mellow|NF Crazy',
		manufacturer: 'Mellow',
		name: 'NF Crazy',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 18.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 41 as Dollars
	},
	{
		id: 'Mellow|NF Crazy HF',
		manufacturer: 'Mellow',
		name: 'NF Crazy HF',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 25 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 44 as Dollars
	},
	{
		id: 'Mellow|NF Crazy HF Volcano',
		manufacturer: 'Mellow',
		name: 'NF Crazy HF Volcano',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 34.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 50 as Dollars
	},
	{
		id: 'Mellow|NF Crazy Volcano',
		manufacturer: 'Mellow',
		name: 'NF Crazy Volcano',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 28 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 48 as Dollars
	},
	{
		id: 'Metaform|Pico Hotend',
		manufacturer: 'Metaform',
		name: 'Pico Hotend',
		ecosystem: 'V6',
		mountingPattern: 'Groove',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius },
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 20.55 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 100 as Dollars
	},
	{
		id: 'Microswiss|Flowtech',
		manufacturer: 'Microswiss',
		name: 'Flowtech',
		ecosystem: 'Various',
		mountingPattern: 'Various',
		nozzle: 'Proprietary',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 28.6 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 80 as Dollars
	},
	{
		id: 'Peopoly|Lancer Long',
		manufacturer: 'Peopoly',
		name: 'Lancer Long',
		ecosystem: 'Lancer',
		mountingPattern: 'Lancer',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 45 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 37.5 as Dollars
	},
	{
		id: 'Peopoly|Lancer Short',
		manufacturer: 'Peopoly',
		name: 'Lancer Short',
		ecosystem: 'Lancer',
		mountingPattern: 'Lancer',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 28 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 22.5 as Dollars
	},
	{
		id: 'Peopoly|Lancer Standard',
		manufacturer: 'Peopoly',
		name: 'Lancer Standard',
		ecosystem: 'Lancer',
		mountingPattern: 'Lancer',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 36.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 30 as Dollars
	},
	{
		id: 'Phaetus|Dragon',
		manufacturer: 'Phaetus',
		name: 'Dragon',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 26 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 55 as Dollars
	},
	{
		id: 'Phaetus|Dragon HF',
		manufacturer: 'Phaetus',
		name: 'Dragon HF',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 33.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 60 as Dollars
	},
	{
		id: 'Phaetus|Dragon Volcano',
		manufacturer: 'Phaetus',
		name: 'Dragon Volcano',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 34.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 65 as Dollars
	},
	{
		id: 'Phaetus|Dragon Volcano UHF',
		manufacturer: 'Phaetus',
		name: 'Dragon Volcano UHF',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 35.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 70 as Dollars
	},
	{
		id: 'Phaetus|Dragon Volcano UUHF',
		manufacturer: 'Phaetus',
		name: 'Dragon Volcano UUHF',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6 Volcano',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius },
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 43 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 75 as Dollars
	},
	{
		id: 'Phaetus|Dragonfly BMS',
		manufacturer: 'Phaetus',
		name: 'Dragonfly BMS',
		ecosystem: null,
		mountingPattern: 'MK8',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 35 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 37.6 as Dollars
	},
	{
		id: 'Phaetus|Rapido UHF',
		manufacturer: 'Phaetus',
		name: 'Rapido UHF',
		ecosystem: 'Rapido',
		mountingPattern: 'Dragon',
		nozzle: 'V6 Volcano',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 34 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 90 as Dollars
	},
	{
		id: 'Plasmics|INo Trident',
		manufacturer: 'Plasmics',
		name: 'INo Trident',
		ecosystem: null,
		mountingPattern: null,
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 17.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 450 as Dollars
	},
	{
		id: 'Qidi|Xmax 3',
		manufacturer: 'Qidi',
		name: 'Xmax 3',
		ecosystem: 'Qidi',
		mountingPattern: 'X1C',
		nozzle: 'Proprietary',
		mzeCompatible: false,
		hfNozzleCompatible: false,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 23.7 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 35 as Dollars
	},
	{
		id: 'Slice Engineering|Mosquito',
		manufacturer: 'Slice Engineering',
		name: 'Mosquito',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 18.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 150 as Dollars
	},
	{
		id: 'Slice Engineering|Mosquito Magnum',
		manufacturer: 'Slice Engineering',
		name: 'Mosquito Magnum',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 25 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 175 as Dollars
	},
	{
		id: 'Slice Engineering|Mosquito Magnum+',
		manufacturer: 'Slice Engineering',
		name: 'Mosquito Magnum+',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 38.7 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 369 as Dollars
	},
	{
		id: 'Slice Engineering|Mosquito Magnum+ HF',
		manufacturer: 'Slice Engineering',
		name: 'Mosquito Magnum+ HF',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 45.2 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 423 as Dollars
	},
	{
		id: 'Slice Engineering|Mosquito Prime',
		manufacturer: 'Slice Engineering',
		name: 'Mosquito Prime',
		ecosystem: 'Mosquito',
		mountingPattern: 'Mosquito',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 66.7 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 1577 as Dollars
	},
	{
		id: 'Trianglelab|CHC XL',
		manufacturer: 'Trianglelab',
		name: 'CHC XL',
		ecosystem: null,
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 330 as Celsius }
		],
		meltZoneLength: 51.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 67 as Dollars
	},
	{
		id: 'Trianglelab|CHC XP1',
		manufacturer: 'Trianglelab',
		name: 'CHC XP1',
		ecosystem: 'X1C',
		mountingPattern: 'X1C',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 35 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 44 as Dollars
	},
	{
		id: 'Trianglelab|Dragon Ace',
		manufacturer: 'Trianglelab',
		name: 'Dragon Ace',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 350 as Celsius }
		],
		meltZoneLength: 36.2 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 80 as Dollars
	},
	{
		id: 'Trianglelab|Dragon Ace Volcano',
		manufacturer: 'Trianglelab',
		name: 'Dragon Ace Volcano',
		ecosystem: 'Dragon',
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 44.7 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 85 as Dollars
	},
	{
		id: 'Trianglelab|STD6-LC',
		manufacturer: 'Trianglelab',
		name: 'STD6-LC',
		ecosystem: null,
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Al', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 51.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 116.5 as Dollars
	},
	{
		id: 'Unknown|Lattice Hotend',
		manufacturer: 'Unknown',
		name: 'Lattice Hotend',
		ecosystem: null,
		mountingPattern: null,
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 57.9 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: null
	},
	{
		id: 'Unknown|MK8',
		manufacturer: 'Unknown',
		name: 'MK8',
		ecosystem: 'MK8',
		mountingPattern: 'MK8',
		nozzle: 'MK8',
		mzeCompatible: false,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: false,
		blockOptions: [
			{ material: 'Al', maxTemperature: 500 as Celsius },
			{ material: 'Cu', maxTemperature: 300 as Celsius }
		],
		meltZoneLength: 18.8 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 8 as Dollars
	},
	{
		id: 'Unknown|Tricorn',
		manufacturer: 'Unknown',
		name: 'Tricorn',
		ecosystem: null,
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 53 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 200 as Dollars
	},
	{
		id: 'Unknown|V9',
		manufacturer: 'Unknown',
		name: 'V9',
		ecosystem: null,
		mountingPattern: 'Dragon',
		nozzle: 'V6',
		mzeCompatible: true,
		hfNozzleCompatible: true,
		nonstructuralHeatbreak: true,
		blockOptions: [
			{ material: 'Cu', maxTemperature: 500 as Celsius }
		],
		meltZoneLength: 39.5 as Millimeter,
		filamentDiameter: 1.75 as Millimeter,
		price: 220 as Dollars
	}
];
