import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Turns the CSVs in this directory into the generated databases in `src/lib`.
 *
 * The app ships the generated `.ts` files rather than parsing CSV at runtime: the data is small,
 * it never changes without a commit, and this way a malformed row is a build failure instead of a
 * blank screen. Run `pnpm data:update-db` after editing either CSV, and commit both sides.
 */

const root = process.cwd();
const HOTEND_CSV = path.join(root, 'data/hotend data.csv');
const MATERIAL_CSV = path.join(root, 'data/materials.csv');
const HOTEND_OUT = path.join(root, 'src/lib/hotend-db.ts');
const MATERIAL_OUT = path.join(root, 'src/lib/material-db.ts');

const GENERATED_HEADER = (source: string) =>
	`// Generated by \`pnpm data:update-db\` from \`${source}\`. Do not edit by hand.\n`;

/** Minimal RFC4180-ish reader: quoted fields with embedded commas, no embedded newlines */
function parseCsv(contents: string): string[][] {
	return contents
		.split(/\r?\n/)
		.filter((line) => line.trim().length > 0)
		.map((line) => {
			const fields: string[] = [];
			let field = '';
			let quoted = false;

			for (let index = 0; index < line.length; index++) {
				const character = line[index];

				if (quoted) {
					if (character === '"') {
						if (line[index + 1] === '"') {
							field += '"';
							index++;
						} else {
							quoted = false;
						}
					} else {
						field += character;
					}
				} else if (character === '"') {
					quoted = true;
				} else if (character === ',') {
					fields.push(field.trim());
					field = '';
				} else {
					field += character;
				}
			}

			fields.push(field.trim());
			return fields;
		});
}

function rowsWithHeaders(contents: string): Record<string, string>[] {
	const [headers, ...rows] = parseCsv(contents);
	if (!headers) throw new Error('empty CSV');

	return rows.map((row) => Object.fromEntries(headers.map((header, index) => [header, row[index] ?? ''])));
}

function required(row: Record<string, string>, column: string, context: string): string {
	const value = row[column];
	if (!value) throw new Error(`${context}: missing "${column}"`);

	return value;
}

function requiredNumber(row: Record<string, string>, column: string, context: string): number {
	const value = Number(required(row, column, context));
	if (!Number.isFinite(value)) throw new Error(`${context}: "${column}" is not a number`);

	return value;
}

/** `null` rather than `''` for the columns that are genuinely unknown for some hotends */
function optional(row: Record<string, string>, column: string): string | null {
	const value = row[column];
	return value ? value : null;
}

/** A blank cell means "nobody knows", which is different from zero and has to survive as `null` */
function optionalNumber(row: Record<string, string>, column: string, context: string): number | null {
	const raw = optional(row, column);
	if (raw === null) return null;

	const value = Number(raw);
	if (!Number.isFinite(value)) throw new Error(`${context}: "${column}" is not a number`);

	return value;
}

/** Single-quoted, because that is what the repo's prettier config emits */
function str(value: string): string {
	return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function literal(value: string | null): string {
	return value === null ? 'null' : str(value);
}

const BLOCK_MATERIALS: Record<string, string> = { Cu: 'copper', Br: 'brass', Al: 'aluminium', St: 'steel' };

/** A share of the melt zone's ceiling, so anything outside (0, 1] is a typo rather than an opinion */
function factor(row: Record<string, string>, context: string): number {
	const value = requiredNumber(row, 'Practical flow factor', context);
	if (!(value > 0) || value > 1) throw new Error(`${context}: practical flow factor ${value} is not in (0, 1]`);

	return value;
}

/**
 * Block material and max temperature are slash-separated lists, paired positionally, with the
 * first entry the stock option: `Cu/Al` with `500/300` is a copper block rated to 500 °C and an
 * aluminium one rated to 300 °C.
 */
function parseBlockOptions(row: Record<string, string>, context: string) {
	const materials = required(row, 'Block Material', context).split('/');
	const temperatures = required(row, 'Max temp', context).split('/');

	if (materials.length !== temperatures.length) {
		throw new Error(`${context}: ${materials.length} block materials but ${temperatures.length} max temps`);
	}

	return materials.map((material, index) => {
		const key = material.trim();
		if (!BLOCK_MATERIALS[key]) {
			throw new Error(`${context}: unknown block material "${key}" (expected ${Object.keys(BLOCK_MATERIALS)})`);
		}

		const maxTemperature = Number(temperatures[index]);
		if (!Number.isFinite(maxTemperature)) throw new Error(`${context}: max temp "${temperatures[index]}" is not a number`);

		return { material: key, maxTemperature };
	});
}

async function generateHotends() {
	const rows = rowsWithHeaders(await readFile(HOTEND_CSV, 'utf8'));

	const hotends = rows.map((row, index) => {
		const context = `hotend row ${index + 2}`;
		const name = required(row, 'Hotend', context);
		// Several rows are community designs with no manufacturer attached; they still need a
		// stable id, because share links reference hotends by `manufacturer|name`
		const manufacturer = optional(row, 'Manufacturer') ?? 'Unknown';

		return {
			id: `${manufacturer}|${name}`,
			manufacturer,
			name,
			ecosystem: optional(row, 'Ecosystem'),
			mountingPattern: optional(row, 'Mounting Pattern'),
			nozzle: optional(row, 'Nozzle'),
			mzeCompatible: required(row, 'MZE compatible', context).toUpperCase() === 'Y',
			hfNozzleCompatible: required(row, 'HF nozzle compatible', context).toUpperCase() === 'Y',
			nonstructuralHeatbreak: required(row, 'Nonstructural heatbreak', context).toUpperCase() === 'Y',
			blockOptions: parseBlockOptions(row, context),
			meltZoneLength: requiredNumber(row, 'Melt zone', context),
			// Blank means the 1.75 mm nearly everything takes, so only the odd one out needs a value
			filamentDiameter: optionalNumber(row, 'Filament (mm)', context) ?? 1.75,
			// Blank means one bore, which is nearly every hotend ever made
			filamentPaths: optionalNumber(row, 'Filament paths', context) ?? 1,
			price: optionalNumber(row, 'Price (USD)', context),
			// What a CHT-style nozzle adds over the stock one, applied only when that option is ticked
			hfNozzlePrice: optionalNumber(row, 'CHT price (USD)', context),
			// ` · ` separates independent notes; a parenthetical renders in the warning colour. Quote
			// the cell if it ever needs a comma, or every column after it shifts
			notes: optional(row, 'Notes')
		};
	});

	const ids = new Set<string>();
	for (const hotend of hotends) {
		if (ids.has(hotend.id)) throw new Error(`duplicate hotend id: ${hotend.id}`);
		ids.add(hotend.id);
	}

	hotends.sort((a, b) => a.id.localeCompare(b.id));

	const body = hotends
		.map(
			(hotend) =>
				`\t{\n` +
				`\t\tid: ${str(hotend.id)},\n` +
				`\t\tmanufacturer: ${str(hotend.manufacturer)},\n` +
				`\t\tname: ${str(hotend.name)},\n` +
				`\t\tecosystem: ${literal(hotend.ecosystem)},\n` +
				`\t\tmountingPattern: ${literal(hotend.mountingPattern)},\n` +
				`\t\tnozzle: ${literal(hotend.nozzle)},\n` +
				`\t\tmzeCompatible: ${hotend.mzeCompatible},\n` +
				`\t\thfNozzleCompatible: ${hotend.hfNozzleCompatible},\n` +
				`\t\tnonstructuralHeatbreak: ${hotend.nonstructuralHeatbreak},\n` +
				`\t\tblockOptions: [\n` +
				hotend.blockOptions
					.map(
						(option) =>
							`\t\t\t{ material: ${str(option.material)}, maxTemperature: ${option.maxTemperature} as Celsius }`
					)
					.join(',\n') +
				`\n\t\t],\n` +
				`\t\tmeltZoneLength: ${hotend.meltZoneLength} as Millimeter,\n` +
				`\t\tfilamentDiameter: ${hotend.filamentDiameter} as Millimeter,\n` +
				`\t\tfilamentPaths: ${hotend.filamentPaths},\n` +
				`\t\tprice: ${hotend.price === null ? 'null' : `${hotend.price} as Dollars`},\n` +
				`\t\thfNozzlePrice: ${hotend.hfNozzlePrice === null ? 'null' : `${hotend.hfNozzlePrice} as Dollars`},\n` +
				`\t\tnotes: ${literal(hotend.notes)}\n` +
				`\t}`
		)
		.join(',\n');

	await writeFile(
		HOTEND_OUT,
		`${GENERATED_HEADER('data/hotend data.csv')}\nimport type { HotendDefinition } from '@/lib/hotend';\nimport type { Celsius, Dollars, Millimeter } from '@/lib/units';\n\nexport const HOTEND_DB: HotendDefinition[] = [\n${body}\n];\n`
	);

	console.log(`wrote ${hotends.length} hotends -> ${path.relative(root, HOTEND_OUT)}`);
}

async function generateMaterials() {
	const rows = rowsWithHeaders(await readFile(MATERIAL_CSV, 'utf8'));

	const materials = rows.map((row, index) => {
		const context = `material row ${index + 2}`;
		const name = required(row, 'Material', context);

		return {
			id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
			name,
			family: required(row, 'Family', context),
			density: requiredNumber(row, 'Density (g/cm3)', context),
			specificHeatCapacity: requiredNumber(row, 'Specific heat capacity (J/gK)', context),
			heatOfFusion: requiredNumber(row, 'Heat of fusion (J/g)', context),
			meltTemperature: requiredNumber(row, 'Melt temp (C)', context),
			printTemperature: requiredNumber(row, 'Print temp (C)', context),
			startTemperature: requiredNumber(row, 'Start temp (C)', context),
			practicalFlowFactor: factor(row, context),
			notes: optional(row, 'Notes')
		};
	});

	const ids = new Set<string>();
	for (const material of materials) {
		if (ids.has(material.id)) throw new Error(`duplicate material id: ${material.id}`);
		ids.add(material.id);
	}

	const body = materials
		.map(
			(material) =>
				`\t{\n` +
				`\t\tid: ${str(material.id)},\n` +
				`\t\tname: ${str(material.name)},\n` +
				`\t\tfamily: ${str(material.family)},\n` +
				`\t\tdensity: ${material.density} as GramsPerCubicCentimeter,\n` +
				`\t\tspecificHeatCapacity: ${material.specificHeatCapacity} as JoulesPerGramKelvin,\n` +
				`\t\theatOfFusion: ${material.heatOfFusion} as JoulesPerGram,\n` +
				`\t\tmeltTemperature: ${material.meltTemperature} as Celsius,\n` +
				`\t\tprintTemperature: ${material.printTemperature} as Celsius,\n` +
				`\t\tstartTemperature: ${material.startTemperature} as Celsius,\n` +
				`\t\tpracticalFlowFactor: ${material.practicalFlowFactor},\n` +
				`\t\tnotes: ${literal(material.notes)}\n` +
				`\t}`
		)
		.join(',\n');

	await writeFile(
		MATERIAL_OUT,
		`${GENERATED_HEADER('data/materials.csv')}\nimport type { MaterialDefinition } from '@/lib/material';\nimport type {\n\tCelsius,\n\tGramsPerCubicCentimeter,\n\tJoulesPerGram,\n\tJoulesPerGramKelvin\n} from '@/lib/units';\n\nexport const MATERIAL_DB: MaterialDefinition[] = [\n${body}\n];\n`
	);

	console.log(`wrote ${materials.length} materials -> ${path.relative(root, MATERIAL_OUT)}`);
}

await generateHotends();
await generateMaterials();
