import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Turns the CSVs in this directory into the generated databases in `src/lib`.
 *
 * The app ships the generated `.ts` files rather than parsing CSV at runtime: the data is small,
 * it never changes without a commit, and this way a malformed row is a build failure instead of a
 * blank screen. Run `pnpm data:update-db` after editing either CSV, and commit both sides.
 */

const root = process.cwd();
const HOTEND_CSV = path.join(root, 'data/hotend data.csv');
const MATERIAL_CSV = path.join(root, 'data/materials.csv');
const VALIDATION_CSV = path.join(root, 'data/validation.csv');
const HOTEND_OUT = path.join(root, 'src/lib/hotend-db.ts');
const MATERIAL_OUT = path.join(root, 'src/lib/material-db.ts');
const VALIDATION_OUT = path.join(root, 'src/lib/validation-db.ts');

const GENERATED_HEADER = (source: string) =>
	`// Generated by \`pnpm data:update-db\` from \`${source}\`. Do not edit by hand.\n`;

/** Minimal RFC4180-ish reader: quoted fields with embedded commas, no embedded newlines */
function parseCsv(contents: string): string[][] {
	return contents
		.split(/\r?\n/)
		.filter((line) => line.trim().length > 0)
		.map((line) => {
			const fields: string[] = [];
			let field = '';
			let quoted = false;

			for (let index = 0; index < line.length; index++) {
				const character = line[index];

				if (quoted) {
					if (character === '"') {
						if (line[index + 1] === '"') {
							field += '"';
							index++;
						} else {
							quoted = false;
						}
					} else {
						field += character;
					}
				} else if (character === '"') {
					quoted = true;
				} else if (character === ',') {
					fields.push(field.trim());
					field = '';
				} else {
					field += character;
				}
			}

			fields.push(field.trim());
			return fields;
		});
}

function rowsWithHeaders(contents: string): Record<string, string>[] {
	const [headers, ...rows] = parseCsv(contents);
	if (!headers) throw new Error('empty CSV');

	return rows.map((row) => Object.fromEntries(headers.map((header, index) => [header, row[index] ?? ''])));
}

function required(row: Record<string, string>, column: string, context: string): string {
	const value = row[column];
	if (!value) throw new Error(`${context}: missing "${column}"`);

	return value;
}

function requiredNumber(row: Record<string, string>, column: string, context: string): number {
	const value = Number(required(row, column, context));
	if (!Number.isFinite(value)) throw new Error(`${context}: "${column}" is not a number`);

	return value;
}

/** `null` rather than `''` for the columns that are genuinely unknown for some hotends */
function optional(row: Record<string, string>, column: string): string | null {
	const value = row[column];
	return value ? value : null;
}

/** A blank cell means "nobody knows", which is different from zero and has to survive as `null` */
function optionalNumber(row: Record<string, string>, column: string, context: string): number | null {
	const raw = optional(row, column);
	if (raw === null) return null;

	const value = Number(raw);
	if (!Number.isFinite(value)) throw new Error(`${context}: "${column}" is not a number`);

	return value;
}

/** Single-quoted, because that is what the repo's prettier config emits */
function str(value: string): string {
	return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function literal(value: string | null): string {
	return value === null ? 'null' : str(value);
}

const BLOCK_MATERIALS: Record<string, string> = { Cu: 'copper', Br: 'brass', Al: 'aluminium', St: 'steel' };

/** A share of the melt zone's ceiling, so anything outside (0, 1] is a typo rather than an opinion */
function factor(row: Record<string, string>, context: string): number {
	const value = requiredNumber(row, 'Practical flow factor', context);
	if (!(value > 0) || value > 1) throw new Error(`${context}: practical flow factor ${value} is not in (0, 1]`);

	return value;
}

/**
 * Block material and max temperature are slash-separated lists, paired positionally, with the
 * first entry the stock option: `Cu/Al` with `500/300` is a copper block rated to 500 °C and an
 * aluminium one rated to 300 °C.
 */
function parseBlockOptions(row: Record<string, string>, context: string) {
	const materials = required(row, 'Block Material', context).split('/');
	const temperatures = required(row, 'Max temp', context).split('/');

	if (materials.length !== temperatures.length) {
		throw new Error(`${context}: ${materials.length} block materials but ${temperatures.length} max temps`);
	}

	return materials.map((material, index) => {
		const key = material.trim();
		if (!BLOCK_MATERIALS[key]) {
			throw new Error(`${context}: unknown block material "${key}" (expected ${Object.keys(BLOCK_MATERIALS)})`);
		}

		const maxTemperature = Number(temperatures[index]);
		if (!Number.isFinite(maxTemperature))
			throw new Error(`${context}: max temp "${temperatures[index]}" is not a number`);

		return { material: key, maxTemperature };
	});
}

async function generateHotends() {
	const rows = rowsWithHeaders(await readFile(HOTEND_CSV, 'utf8'));

	const hotends = rows.map((row, index) => {
		const context = `hotend row ${index + 2}`;
		const name = required(row, 'Hotend', context);
		// Several rows are community designs with no manufacturer attached; they still need a
		// stable id, because share links reference hotends by `manufacturer|name`
		const manufacturer = optional(row, 'Manufacturer') ?? 'Unknown';

		return {
			id: `${manufacturer}|${name}`,
			manufacturer,
			name,
			ecosystem: optional(row, 'Ecosystem'),
			mountingPattern: optional(row, 'Mounting Pattern'),
			nozzle: optional(row, 'Nozzle'),
			mzeCompatible: required(row, 'MZE compatible', context).toUpperCase() === 'Y',
			hfNozzleCompatible: required(row, 'HF nozzle compatible', context).toUpperCase() === 'Y',
			nonstructuralHeatbreak: required(row, 'Nonstructural heatbreak', context).toUpperCase() === 'Y',
			blockOptions: parseBlockOptions(row, context),
			meltZoneLength: requiredNumber(row, 'Melt zone', context),
			// Blank means "behaves like its dimensions", which is nearly every hotend. Only fill it in
			// where the two genuinely differ
			effectiveMeltZone:
				optionalNumber(row, 'Effective melt zone', context) ?? requiredNumber(row, 'Melt zone', context),
			// Blank means the 1.75 mm nearly everything takes, so only the odd one out needs a value
			filamentDiameter: optionalNumber(row, 'Filament (mm)', context) ?? 1.75,
			// Blank means one bore, which is nearly every hotend ever made
			filamentPaths: optionalNumber(row, 'Filament paths', context) ?? 1,
			// Blank means yes: most hotends are still on sale, and getting this wrong only mislabels
			// a filter rather than distorting a number, so it does not deserve to fail the build
			stillSold: (optional(row, 'Still sold') ?? 'Y').toUpperCase() !== 'N',
			price: optionalNumber(row, 'Price (USD)', context),
			// What a CHT-style nozzle adds over the stock one, applied only when that option is ticked
			hfNozzlePrice: optionalNumber(row, 'CHT price (USD)', context),
			// ` · ` separates independent notes; a parenthetical renders in the warning colour. Quote
			// the cell if it ever needs a comma, or every column after it shifts
			notes: optional(row, 'Notes')
		};
	});

	const ids = new Set<string>();
	for (const hotend of hotends) {
		if (ids.has(hotend.id)) throw new Error(`duplicate hotend id: ${hotend.id}`);
		ids.add(hotend.id);
	}

	hotends.sort((a, b) => a.id.localeCompare(b.id));

	const body = hotends
		.map(
			(hotend) =>
				`\t{\n` +
				`\t\tid: ${str(hotend.id)},\n` +
				`\t\tmanufacturer: ${str(hotend.manufacturer)},\n` +
				`\t\tname: ${str(hotend.name)},\n` +
				`\t\tecosystem: ${literal(hotend.ecosystem)},\n` +
				`\t\tmountingPattern: ${literal(hotend.mountingPattern)},\n` +
				`\t\tnozzle: ${literal(hotend.nozzle)},\n` +
				`\t\tmzeCompatible: ${hotend.mzeCompatible},\n` +
				`\t\thfNozzleCompatible: ${hotend.hfNozzleCompatible},\n` +
				`\t\tnonstructuralHeatbreak: ${hotend.nonstructuralHeatbreak},\n` +
				`\t\tblockOptions: [\n` +
				hotend.blockOptions
					.map(
						(option) =>
							`\t\t\t{ material: ${str(option.material)}, maxTemperature: ${option.maxTemperature} as Celsius }`
					)
					.join(',\n') +
				`\n\t\t],\n` +
				`\t\tmeltZoneLength: ${hotend.meltZoneLength} as Millimeter,\n` +
				`\t\teffectiveMeltZone: ${hotend.effectiveMeltZone} as Millimeter,\n` +
				`\t\tfilamentDiameter: ${hotend.filamentDiameter} as Millimeter,\n` +
				`\t\tfilamentPaths: ${hotend.filamentPaths},\n` +
				`\t\tstillSold: ${hotend.stillSold},\n` +
				`\t\tprice: ${hotend.price === null ? 'null' : `${hotend.price} as Dollars`},\n` +
				`\t\thfNozzlePrice: ${hotend.hfNozzlePrice === null ? 'null' : `${hotend.hfNozzlePrice} as Dollars`},\n` +
				`\t\tnotes: ${literal(hotend.notes)}\n` +
				`\t}`
		)
		.join(',\n');

	await writeFile(
		HOTEND_OUT,
		`${GENERATED_HEADER('data/hotend data.csv')}\nimport type { HotendDefinition } from '@/lib/hotend';\nimport type { Celsius, Dollars, Millimeter } from '@/lib/units';\n\nexport const HOTEND_DB: HotendDefinition[] = [\n${body}\n];\n`
	);

	console.log(`wrote ${hotends.length} hotends -> ${path.relative(root, HOTEND_OUT)}`);

	return hotends;
}

async function generateMaterials() {
	const rows = rowsWithHeaders(await readFile(MATERIAL_CSV, 'utf8'));

	const materials = rows.map((row, index) => {
		const context = `material row ${index + 2}`;
		const name = required(row, 'Material', context);

		return {
			id: name
				.toLowerCase()
				.replace(/[^a-z0-9]+/g, '-')
				.replace(/^-|-$/g, ''),
			name,
			family: required(row, 'Family', context),
			density: requiredNumber(row, 'Density (g/cm3)', context),
			specificHeatCapacity: requiredNumber(row, 'Specific heat capacity (J/gK)', context),
			heatOfFusion: requiredNumber(row, 'Heat of fusion (J/g)', context),
			meltTemperature: requiredNumber(row, 'Melt temp (C)', context),
			printTemperature: requiredNumber(row, 'Print temp (C)', context),
			startTemperature: requiredNumber(row, 'Start temp (C)', context),
			practicalFlowFactor: factor(row, context),
			notes: optional(row, 'Notes')
		};
	});

	const ids = new Set<string>();
	for (const material of materials) {
		if (ids.has(material.id)) throw new Error(`duplicate material id: ${material.id}`);
		ids.add(material.id);
	}

	const body = materials
		.map(
			(material) =>
				`\t{\n` +
				`\t\tid: ${str(material.id)},\n` +
				`\t\tname: ${str(material.name)},\n` +
				`\t\tfamily: ${str(material.family)},\n` +
				`\t\tdensity: ${material.density} as GramsPerCubicCentimeter,\n` +
				`\t\tspecificHeatCapacity: ${material.specificHeatCapacity} as JoulesPerGramKelvin,\n` +
				`\t\theatOfFusion: ${material.heatOfFusion} as JoulesPerGram,\n` +
				`\t\tmeltTemperature: ${material.meltTemperature} as Celsius,\n` +
				`\t\tprintTemperature: ${material.printTemperature} as Celsius,\n` +
				`\t\tstartTemperature: ${material.startTemperature} as Celsius,\n` +
				`\t\tpracticalFlowFactor: ${material.practicalFlowFactor},\n` +
				`\t\tnotes: ${literal(material.notes)}\n` +
				`\t}`
		)
		.join(',\n');

	await writeFile(
		MATERIAL_OUT,
		`${GENERATED_HEADER('data/materials.csv')}\nimport type { MaterialDefinition } from '@/lib/material';\nimport type {\n\tCelsius,\n\tGramsPerCubicCentimeter,\n\tJoulesPerGram,\n\tJoulesPerGramKelvin\n} from '@/lib/units';\n\nexport const MATERIAL_DB: MaterialDefinition[] = [\n${body}\n];\n`
	);

	console.log(`wrote ${materials.length} materials -> ${path.relative(root, MATERIAL_OUT)}`);

	return materials;
}

type Named = { id: string; name: string };
type Blocked = Named & { blockOptions: { material: string }[] };

/** Tests name a hotend or a filament the way their source did, so the match is case-insensitive */
function resolve<T extends Named>(entries: T[], name: string, kind: string, context: string): T {
	const wanted = name.trim().toLowerCase();
	const match = entries.find((entry) => entry.name.toLowerCase() === wanted);
	if (!match) throw new Error(`${context}: no ${kind} named "${name}"`);

	return match;
}

/**
 * Which block variant the test ran on, or `null` for whatever that hotend ships as.
 *
 * Blank is the ordinary case and means the stock option, which is already what the model falls back
 * to, so no row has to restate a default. A filled cell has to name a variant the hotend is actually
 * sold in: a copper Revo is not a thing, and quietly modelling one would put a prediction on the
 * charts that no hardware could have produced.
 */
function parseBlock(row: Record<string, string>, hotend: Blocked, context: string): string | null {
	const value = optional(row, 'Block');
	if (!value) return null;

	const wanted = value.trim().toLowerCase();
	const key = Object.keys(BLOCK_MATERIALS).find(
		(code) => code.toLowerCase() === wanted || BLOCK_MATERIALS[code] === wanted
	);
	if (!key) {
		throw new Error(
			`${context}: unknown block material "${value}" (expected ${Object.keys(BLOCK_MATERIALS).join(', ')})`
		);
	}

	if (!hotend.blockOptions.some((option) => option.material === key)) {
		const sold = hotend.blockOptions.map((option) => BLOCK_MATERIALS[option.material]).join(', ');
		throw new Error(`${context}: ${hotend.name} has no ${BLOCK_MATERIALS[key]} block (it comes in ${sold})`);
	}

	return key;
}

/**
 * One number per test, from whichever columns the source filled in.
 *
 * A reported midpoint is taken as it stands. A start and an end bracket the same transition rather
 * than marking two events, so they average. A row with one figure is that figure, whichever column
 * it sits in — sources disagree about which end of the failure they quote, and splitting the set by
 * that convention would compare reporting styles instead of hotends.
 */
function measuredFlow(row: Record<string, string>, context: string): { flow: number; basis: string } {
	const value = (column: string) => {
		const parsed = optionalNumber(row, column, context);

		return parsed !== null && parsed > 0 ? parsed : null;
	};

	const start = value('Start (mm3/s)');
	const median = value('Median (mm3/s)');
	const end = value('End (mm3/s)');

	if (median !== null) return { flow: median, basis: 'median' };
	if (start !== null && end !== null) return { flow: (start + end) / 2, basis: 'start+end' };
	if (start !== null) return { flow: start, basis: 'start' };
	if (end !== null) return { flow: end, basis: 'end' };

	throw new Error(`${context}: no flow measurement`);
}

/** A link is named by its host; anything else is the name of the source itself, e.g. `author` */
function citationSource(citation: string): string {
	try {
		return new URL(citation).hostname.replace(/^www\./, '');
	} catch {
		return citation;
	}
}

async function generateValidation(hotends: Blocked[], materials: Named[]) {
	const rows = rowsWithHeaders(await readFile(VALIDATION_CSV, 'utf8'));

	const measurements = rows.map((row, index) => {
		const context = `validation row ${index + 2}`;
		const { flow, basis } = measuredFlow(row, context);
		const citation = required(row, 'Citation', context);
		const hotend = resolve(hotends, required(row, 'Hotend', context), 'hotend', context);

		return {
			// Positional: nothing outside the file references these, and two tests can otherwise
			// differ only in a figure that is the thing being compared
			id: `v${index + 1}`,
			hotendId: hotend.id,
			materialId: resolve(materials, required(row, 'Filament', context), 'material', context).id,
			block: parseBlock(row, hotend, context),
			subtype: optional(row, 'Subtype'),
			brand: optional(row, 'Filament manufacturer'),
			extruder: optional(row, 'Extruder'),
			nozzleDiameter: requiredNumber(row, 'Nozzle diameter (mm)', context),
			temperature: requiredNumber(row, 'Temperature', context),
			mze: required(row, 'MZE', context).toUpperCase() === 'Y',
			cht: required(row, 'CHT', context).toUpperCase() === 'Y',
			flow,
			basis,
			citation,
			source: citationSource(citation)
		};
	});

	const body = measurements
		.map(
			(measurement) =>
				`\t{\n` +
				`\t\tid: ${str(measurement.id)},\n` +
				`\t\thotendId: ${str(measurement.hotendId)},\n` +
				`\t\tmaterialId: ${str(measurement.materialId)},\n` +
				`\t\tblock: ${literal(measurement.block)},\n` +
				`\t\tsubtype: ${literal(measurement.subtype)},\n` +
				`\t\tbrand: ${literal(measurement.brand)},\n` +
				`\t\textruder: ${literal(measurement.extruder)},\n` +
				`\t\tnozzleDiameter: ${measurement.nozzleDiameter},\n` +
				`\t\ttemperature: ${measurement.temperature} as Celsius,\n` +
				`\t\tmze: ${measurement.mze},\n` +
				`\t\tcht: ${measurement.cht},\n` +
				`\t\tflow: ${Number(measurement.flow.toFixed(3))},\n` +
				`\t\tbasis: ${str(measurement.basis)},\n` +
				`\t\tcitation: ${str(measurement.citation)},\n` +
				`\t\tsource: ${str(measurement.source)}\n` +
				`\t}`
		)
		.join(',\n');

	await writeFile(
		VALIDATION_OUT,
		`${GENERATED_HEADER('data/validation.csv')}\nimport type { Celsius } from '@/lib/units';\nimport type { ValidationMeasurement } from '@/lib/validation';\n\nexport const VALIDATION_DB: ValidationMeasurement[] = [\n${body}\n];\n`
	);

	console.log(`wrote ${measurements.length} measurements -> ${path.relative(root, VALIDATION_OUT)}`);
}

const hotends = await generateHotends();
const materials = await generateMaterials();
await generateValidation(hotends, materials);
